import { ApiError, del, eq, insert, json, one, patch, rows, rpc } from './db.ts';
import { authenticate, canBuild, isAdmin, projectAccess } from './auth.ts';
import { deleteObject, deletePrefix, headObject, moveObject, presign, ready } from './s3.ts';

function route(req:Request){const p=new URL(req.url).pathname,m='/qa-files',i=p.indexOf(m);return(i>=0?p.slice(i+m.length):p)||'/';}
async function body(req:Request){try{return await req.json();}catch{return {};}}
function cleanName(v:string){const s=v.replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').replace(/\s+/g,' ').trim();return(s||'dosya.bin').slice(0,180);}
function media(v:any){return String(v||'application/octet-stream').slice(0,100);}
function size(v:any){const n=Number(v);return Number.isFinite(n)&&n>=0?Math.floor(n):null;}
function sha(v:any){const s=String(v||'').toLowerCase();return/^[0-9a-f]{64}$/.test(s)?s:null;}
async function bug(id:string){const b=await one('bug_reports',`select=id,public_key,project_id,reporter_id&id=${eq(id)}`);if(!b)throw new ApiError(404,'Hata raporu bulunamadı.');return b;}
async function retest(id:string){const r=await one('retest_requests',`select=id,bug_report_id&id=${eq(id)}`);if(!r)throw new ApiError(404,'Yeniden test talebi bulunamadı.');return{r,b:await bug(r.bug_report_id)};}
async function verifyUploaded(path:string, expectedSize:number|null){const h=await headObject(path);if(expectedSize!==null&&h.size!==expectedSize)throw new ApiError(409,`HF üzerindeki dosya boyutu beklenen değerle eşleşmiyor (${h.size}/${expectedSize}).`);}

Deno.serve(async req=>{try{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'}});
  const r=route(req);
  if(r==='/'||r==='/health')return json({status:'ok',s3_ready:await ready(),storage:'xykeskin/dmc-turkish-dub-qa-archive'});
  const u=await authenticate(req);let m;

  m=r.match(/^\/bugs\/([^/]+)\/evidence\/init$/);
  if(m&&req.method==='POST'){const b=await bug(m[1]);await projectAccess(u,b.project_id);if(!isAdmin(u)&&u.id!==b.reporter_id)throw new ApiError(403,'Bu rapora kanıt yükleme yetkiniz yok.');const x=await body(req),id=crypto.randomUUID(),fn=cleanName(String(x.filename||'video.mp4')),path=`projects/${b.project_id}/reports/${b.public_key}/evidence/${id}/${fn}`;return json({upload_id:id,upload_url:await presign('PUT',path,3600),storage_path:path,filename:fn});}
  m=r.match(/^\/bugs\/([^/]+)\/evidence\/finalize$/);
  if(m&&req.method==='POST'){const b=await bug(m[1]);await projectAccess(u,b.project_id);if(!isAdmin(u)&&u.id!==b.reporter_id)throw new ApiError(403,'Bu rapora kanıt ekleme yetkiniz yok.');const x=await body(req),path=String(x.storage_path||''),expected=size(x.size_bytes);if(!path.startsWith(`projects/${b.project_id}/reports/${b.public_key}/evidence/`))throw new ApiError(400,'Kanıt storage yolu geçersiz.');await verifyUploaded(path,expected);const a=await insert('evidence_assets',{project_id:b.project_id,owner_type:'bug_report',owner_id:b.id,storage_path:path,original_filename:cleanName(String(x.filename||'video.mp4')),media_type:media(x.media_type),size_bytes:expected,sha256:sha(x.sha256),uploaded_by:u.id});return json({id:a.id,filename:a.original_filename,media_type:a.media_type,size_bytes:a.size_bytes,sha256:a.sha256,storage_path:a.storage_path},201);}

  m=r.match(/^\/retests\/([^/]+)\/evidence\/init$/);
  if(m&&req.method==='POST'){const{r:rr,b}=await retest(m[1]);await projectAccess(u,b.project_id);if(!isAdmin(u)){const a=await one('retest_assignees',`select=id&retest_request_id=${eq(rr.id)}&user_id=${eq(u.id)}`);if(!a)throw new ApiError(403,'Bu yeniden test size atanmadı.');}const x=await body(req),id=crypto.randomUUID(),fn=cleanName(String(x.filename||'retest.mp4')),path=`projects/${b.project_id}/retests/${rr.id}/evidence/${id}/${fn}`;return json({upload_id:id,upload_url:await presign('PUT',path,3600),storage_path:path,filename:fn});}
  m=r.match(/^\/retests\/([^/]+)\/evidence\/finalize$/);
  if(m&&req.method==='POST'){const{r:rr,b}=await retest(m[1]);await projectAccess(u,b.project_id);if(!isAdmin(u)){const a=await one('retest_assignees',`select=id&retest_request_id=${eq(rr.id)}&user_id=${eq(u.id)}`);if(!a)throw new ApiError(403,'Bu yeniden test size atanmadı.');}const x=await body(req),path=String(x.storage_path||''),expected=size(x.size_bytes);if(!path.startsWith(`projects/${b.project_id}/retests/${rr.id}/evidence/`))throw new ApiError(400,'Yeniden test storage yolu geçersiz.');await verifyUploaded(path,expected);const a=await insert('evidence_assets',{project_id:b.project_id,owner_type:'retest_request',owner_id:rr.id,storage_path:path,original_filename:cleanName(String(x.filename||'retest.mp4')),media_type:media(x.media_type),size_bytes:expected,sha256:sha(x.sha256),uploaded_by:u.id});return json({id:a.id,filename:a.original_filename,media_type:a.media_type,size_bytes:a.size_bytes,sha256:a.sha256,storage_path:a.storage_path},201);}

  m=r.match(/^\/projects\/([^/]+)\/builds\/([^/]+)\/file\/init$/);
  if(m&&req.method==='POST'){if(!canBuild(u))throw new ApiError(403,'Build yükleme yetkiniz yok.');await projectAccess(u,m[1],true);const b=await one('builds',`select=id,project_id&id=${eq(m[2])}&project_id=${eq(m[1])}`);if(!b)throw new ApiError(404,'Test sürümü bulunamadı.');const x=await body(req),fn=cleanName(String(x.filename||'build.bin')),path=`projects/${m[1]}/builds/active/${m[2]}/${fn}`;return json({upload_url:await presign('PUT',path,3600),storage_path:path,filename:fn});}
  m=r.match(/^\/projects\/([^/]+)\/builds\/([^/]+)\/file\/finalize$/);
  if(m&&req.method==='POST'){if(!canBuild(u))throw new ApiError(403,'Build yükleme yetkiniz yok.');await projectAccess(u,m[1],true);const b=await one('builds',`select=id,project_id&id=${eq(m[2])}&project_id=${eq(m[1])}`);if(!b)throw new ApiError(404,'Test sürümü bulunamadı.');const x=await body(req),path=String(x.storage_path||''),expected=size(x.size_bytes);if(!path.startsWith(`projects/${m[1]}/builds/active/${m[2]}/`))throw new ApiError(400,'Build storage yolu geçersiz.');await verifyUploaded(path,expected);await patch('builds',`id=${eq(m[2])}`,{storage_path:path,original_filename:cleanName(String(x.filename||'build.bin')),size_bytes:expected,sha256:sha(x.sha256),status:'candidate'});await insert('build_events',{build_id:m[2],user_id:u.id,event_type:'upload_completed',metadata_json:{storage_path:path}});return json({status:'candidate',storage_path:path});}

  m=r.match(/^\/projects\/([^/]+)\/builds\/([^/]+)\/archive$/);
  if(m&&req.method==='POST'){if(!isAdmin(u))throw new ApiError(403,'Test sürümünü yalnızca yönetici arşivleyebilir.');await projectAccess(u,m[1],true);const b=await one('builds',`select=*&id=${eq(m[2])}&project_id=${eq(m[1])}`);if(!b)throw new ApiError(404,'Test sürümü bulunamadı.');if(b.status==='current')throw new ApiError(409,'Güncel test sürümü doğrudan arşivlenemez.');if(b.status==='archived')return json({status:'archived',storage_path:b.storage_path});if(!b.storage_path)throw new ApiError(409,'Dosyası bulunmayan test sürümü arşivlenemez.');const activeTasks=await rows('tasks',`select=id&required_build_id=${eq(b.id)}&status=eq.open`);if(activeTasks.length)throw new ApiError(409,'Bu build aktif görevlerde kullanıldığı için arşivlenemez.');const marker='/builds/active/';if(!String(b.storage_path).includes(marker))throw new ApiError(409,'Build dosyası active namespace içinde değil.');const destination=String(b.storage_path).replace(marker,'/builds/archived/');await moveObject(String(b.storage_path),destination);await patch('builds',`id=${eq(b.id)}`,{storage_path:destination,status:'archived',archived_at:new Date().toISOString()});await insert('build_events',{build_id:b.id,user_id:u.id,event_type:'archived',metadata_json:{source_path:b.storage_path,storage_path:destination}});return json({status:'archived',storage_path:destination});}

  m=r.match(/^\/projects\/([^/]+)\/builds\/([^/]+)\/download$/);
  if(m&&req.method==='GET'){await projectAccess(u,m[1]);const b=await one('builds',`select=storage_path&id=${eq(m[2])}&project_id=${eq(m[1])}`);if(!b?.storage_path)throw new ApiError(404,'Build dosyası bulunamadı.');return new Response(null,{status:302,headers:{Location:await presign('GET',b.storage_path,3600)}});}
  m=r.match(/^\/evidence\/([^/]+)\/download$/);
  if(m&&req.method==='GET'){const a=await one('evidence_assets',`select=id,project_id,storage_path&id=${eq(m[1])}`);if(!a)throw new ApiError(404,'Kanıt dosyası bulunamadı.');await projectAccess(u,a.project_id);return new Response(null,{status:302,headers:{Location:await presign('GET',a.storage_path,3600)}});}
  m=r.match(/^\/evidence\/([^/]+)$/);
  if(m&&req.method==='DELETE'){if(!isAdmin(u))throw new ApiError(403,'Kanıt dosyasını yalnızca yönetici kalıcı olarak silebilir.');const a=await one('evidence_assets',`select=id,project_id,storage_path,original_filename&id=${eq(m[1])}`);if(!a)throw new ApiError(404,'Kanıt dosyası bulunamadı.');await projectAccess(u,a.project_id,true);const prefix=`projects/${a.project_id}/`;if(!String(a.storage_path||'').startsWith(prefix))throw new ApiError(409,'Kanıt storage yolu proje alanıyla eşleşmiyor.');await deleteObject(String(a.storage_path));const removed=await del('evidence_assets',`id=${eq(a.id)}&project_id=${eq(a.project_id)}`);if(!removed.length)throw new ApiError(502,'Kanıt dosyası HF’den silindi ancak veritabanı kaydı kaldırılamadı.');return json({status:'deleted',id:a.id,filename:a.original_filename});}

  m=r.match(/^\/bugs\/([^/]+)$/);
  if(m&&req.method==='DELETE'){if(!isAdmin(u))throw new ApiError(403,'Hata raporunu yalnızca yönetici kalıcı olarak silebilir.');const b=await bug(m[1]);await projectAccess(u,b.project_id,true);const retests=await rows('retest_requests',`select=id&bug_report_id=${eq(b.id)}`);await deletePrefix(`projects/${b.project_id}/reports/${b.public_key}/`);for(const rr of retests)await deletePrefix(`projects/${b.project_id}/retests/${rr.id}/`);await del('evidence_assets',`project_id=${eq(b.project_id)}&owner_type=eq.bug_report&owner_id=${eq(b.id)}`);for(const rr of retests)await del('evidence_assets',`project_id=${eq(b.project_id)}&owner_type=eq.retest_request&owner_id=${eq(rr.id)}`);const removed=await del('bug_reports',`id=${eq(b.id)}&project_id=${eq(b.project_id)}`);if(!removed.length)throw new ApiError(502,'Hata raporu veritabanından silinemedi.');return json({status:'deleted',id:b.id,key:b.public_key});}

  m=r.match(/^\/projects\/([^/]+)$/);
  if(m&&req.method==='DELETE'){if(!isAdmin(u))throw new ApiError(403,'Projeyi yalnızca yönetici kalıcı olarak silebilir.');const p=await one('projects',`select=id,name,status&id=${eq(m[1])}`);if(!p)throw new ApiError(404,'Proje bulunamadı.');const x=await body(req);if(String(x.project_name||'')!==p.name)throw new ApiError(400,'Proje adı doğrulaması eşleşmiyor.');if(p.status!=='closed'&&p.status!=='purge_pending')await patch('projects',`id=${eq(p.id)}`,{status:'closed',closed_at:new Date().toISOString()});const deletedStorage=await deletePrefix(`projects/${p.id}/`);await rpc('qa_finalize_project_purge',{p_project_id:p.id,p_requested_by:u.id,p_approved_by:u.id,p_storage_deleted_bytes:deletedStorage.bytes});await del('project_purge_audits',`project_id=${eq(p.id)}`);return json({status:'deleted',project_id:p.id,storage_deleted_bytes:deletedStorage.bytes,storage_deleted_objects:deletedStorage.count});}

  throw new ApiError(404,'Dosya API yolu bulunamadı.');
}catch(e){if(e instanceof ApiError)return json({detail:e.message},e.status);console.error('qa-files',e);return json({detail:'Dosya servisinde beklenmeyen bir hata oluştu.'},500);}});
